title: Sai Bhargav
description: Portfolio Website
baseurl: "" 
url: "https://saibhargav.github.io"
remote_theme: cotes2020/jekyll-theme-chirpy
markdown: kramdown
highlighter: rouge
timezone: UTC
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
paginate: 10
paginate_path: "/posts/page:num/"
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      pin: false
  - scope:
      path: "_tabs"
      type: tabs
    values:
      layout: page
author:
  name: Sai Bhargav
  email: saibhargavt@outlook.com
# Social links (optional)
github_username: saibhargav-t
LinkedIn: https://www.linkedin.com/in/saibhargav-t/
